version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@aahmhmm28"
      POSTGRES_DB: wrm_dev_db
    ports:
      - "5431:5431"
    command: [ "postgres", "-p", "5431" ]

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'maryam@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '@aahmhmm28'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - "5050:5050"