spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/wrm_dev_db
    username: postgres
    password: "@aahmhmm28"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true