spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wrm_dev
    username: postgres
    password: @aahmhmm28
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  profiles:
    active: dev
server:
  port: 8080